### ISSUE TITLE
Publish the unstripped version of libflutter_engine.so for debugging

### ISSUE THREAD

**Issue by doesnotexist** [sony/flutter-embedded-linux#293]
Even the debug profile libflutter_engine.so is stripped of debug symbols, but --unoptimized builds of flutter engine should also publish a version in the ninja out directory under a subdirectory called lib.unstripped
It would be helpful to also publish the unstripped libflutter_engine.so  debug artifacts zip.

**Comment by HidenoriMatsubayashi** [comment]
> Even the debug profile libflutter_engine.so is stripped of debug symbols

Yes. This is because it intends to be used for debugging flutter apps with debug mode (not for embedder debugging). The artifacts which are uploaded in https://github.com/sony/flutter-embedded-linux/releases is used for [flutter-elinux](https://github.com/sony/flutter-elinux). Flutter app developers don't usually use debug profile libflutter_engine.so. Developers of flutter engine of embedders must build it by themselves.
